language: node_js
node_js: 
    - '8'

# Travis-CI Caching
cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install google-chrome-stable

before_script:

script:
  - node index --module scw --url ${SCW_URL_1} --uname ${SCW_USER_NAME_1} --pwd ${SCW_USER_PWD_1}
  - node index --module scw --url ${SCW_URL_2} --uname ${SCW_USER_NAME_2} --pwd ${SCW_USER_PWD_2}

branches:
  only:
    - master
env:
 global:
